//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP05Tretyakov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id_Employee { get; set; }
        public string FIO { get; set; }
        public string Department_Name { get; set; }
        public double Labor_Participation_Rate { get; set; }
        public decimal Amount_Employees_Contract { get; set; }
        public string Contract_Number { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Department Department { get; set; }
    }
}
